pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Meditation Enthusiasts
title: Meditation Enthusiasts
description: "A place for Meditators"
url: https://www.meditationenthusiasts.org/
urlnohttp: www.meditationenthusiasts.org/
contact: seth@meditationenthusiasts.org
github: https://github.com/MeditationEnthusiasts/meditationenthusaists.org
githubissues: https://github.com/MeditationEnthusiasts/meditationenthusaists.org/issues

disqus_shortname: meditationenthusiasts-org

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
