pretzel: 
    engine: razor

category_pages_layout: category
subcategory_pages_layout: subcategory
tag_pages_layout: tag
permalink: "/posts/:slug_categories/:slug_subcategory/:title/"

# Site settings
author: Meditation Enthusiasts
title: Meditation Enthusiasts
description: "A place for Meditators"
url: https://www.meditationenthusiasts.org/
urlnohttp: www.meditationenthusiasts.org/
contact: seth@meditationenthusiasts.org
github: https://github.com/MeditationEnthusiasts/meditationenthusaists.org
githubissues: https://github.com/MeditationEnthusiasts/meditationenthusaists.org/issues
website_version: "6.0.0"
disqus_shortname: meditationenthusiasts-org
enable_subcategories: true

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
