pretzel: 
    engine: razor

category_pages_layout: category
subcategory_pages_layout: subcategory
tag_pages_layout: tag
permalink: "/posts/:slug_categories/:slug_subcategory/:title/"

# Site settings
author: Meditation Enthusiasts
title: Meditation Enthusiasts
description: "A place for Meditators"
url: https://www.meditationenthusiasts.org/
urlnohttp: www.meditationenthusiasts.org/
contact: seth@meditationenthusiasts.org
github: https://github.com/MeditationEnthusiasts/meditationenthusaists.org
githubissues: https://github.com/MeditationEnthusiasts/meditationenthusaists.org/issues
website_version: "6.0.0"
disqus_shortname: meditationenthusiasts-org
enable_subcategories: true

# ActivtyPub:
actpub_directory: "activitypub"
actpub_outbox: true
actpub_inbox: true
actpub_profileurl: posts
actpub_username: posts
actpub_icon: "https://www.meditationenthusiasts.org/static/img/logo.jpg"
actpub_created: "2010-07-07T00:00:00.0000000Z"
actpub_summary: "I post whenever there's a new post on Meditation Enthusiasts, a site about Meditation!"
actpub_publickeyfile: "activitypub/public.pem"
actpub_following:
 - "https://www.roclongboarding.info/activitypub/profile.json"
 - "https://tech.lgbt/users/xforever1313"

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
